-- HSQL table creation
-- This file must be UTF-8 encoded.
-- Format is explained in nl.fw.util.jdbc.NamedQuery.loadQueries.
-- The brackets below mark the beginning of a (new) query
--[]
-- since no name is given, query will be named "1" 

create table users (
id bigint generated by default as identity (start with 1), 
name varchar(255), 
primary key (id)
)

--[]
-- query "2"

create table settings (
code varchar(255) not null,
-- Value is a reserved word, must put in quotes.
"value" varchar(2047),
primary key (code)
)
